# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'New-HelloWorld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for New-HelloWorld
  pod 'SnapKit','~> 5.0'

end
